"""
SCM config cloner — sanitise a backup snapshot and replay it into a target
folder / tenant.

Workflow:
  1. Load a backup JSON produced by scm_config_backup.
  2. Sanitise each object: strip system fields, rewrite the folder, scrub PSKs,
     optionally apply a name prefix and anonymise IP addresses.
  3. Push objects to the target tenant in dependency order (tags → addresses →
     groups → profiles → rules → deployment).
  4. Return a detailed push report (or a dry-run preview).

PSK handling: pre-shared keys in IKE gateways are ALWAYS replaced with
  CHANGEME_<gateway-name>  — they must be set manually before committing.

Dependency push order
─────────────────────
Tier 0  tags, services, EDLs, URL categories, server/crypto/sec profiles,
        GP & identity
Tier 1  addresses, service groups, log-forwarding profiles, zone-protection,
        profile groups
Tier 2  address groups, app groups, HIP objects
Tier 3  HIP profiles, security zones
Rules   security (pre), security (post), NAT, decryption, app-override
Deploy  IKE gateways, IPSec tunnels, remote networks, service connections

GlobalProtect coverage: auth settings, tunnel profiles, agent profiles,
forwarding profiles and the portal/gateway infrastructure settings all live
in the fixed 'Mobile Users' folder; SAML/Radius/LDAP auth profiles clone into
the customer folder.  Network infrastructure (crypto/QoS profiles, internal
DNS servers, bandwidth allocations) clones into 'Remote Networks'.
"""

from __future__ import annotations

import copy
import inspect
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from ..utils.logging import get_logger
from .clone_preflight import (
    MISSING_REFERENCE_MODES,
    MISSING_TRUST_CERT_MODES,
    PreflightResult,
    TargetInventory,
    check_references,
    fetch_target_inventory,
)

logger = get_logger(__name__)

# Fields generated by SCM — must not be sent on create
_SYSTEM_FIELDS = frozenset(
    {
        "id",
        "uid",
        "@uid",
        "@loc",
        "audit_comment",
        "modified_at",
        "created_at",
        "modified_by",
        "created_by",
        "last_modified_by",
        "etag",
        # Provenance injected by the extractor, and read-only fields the API
        # returns but every *CreateModel rejects (extra="forbid").
        "_position",
        "_folder",
        "policy_type",
        "rulebase",
    }
)

# Fixed folder names required by the SCM API for deployment resources
_FOLDER_REMOTE_NETWORKS = "Remote Networks"
_FOLDER_SERVICE_CONNECTIONS = "Service Connections"
_FOLDER_MOBILE_USERS = "Mobile Users"

# Push order: (snapshot_attr, sdk_attr, folder_mode)
# folder_mode: "customer" → target_folder, else the literal SCM folder name
_PUSH_ORDER: list[tuple[str, str, str]] = [
    # ── Tier 0: no inter-object dependencies ──────────────────────────────
    ("tags", "tag", "customer"),
    ("services", "service", "customer"),
    ("edls", "external_dynamic_list", "customer"),
    # URL filtering profiles reference custom URL categories by name
    ("url_categories", "url_category", "customer"),
    ("http_server_profiles", "http_server_profile", "customer"),
    ("syslog_profiles", "syslog_server_profile", "customer"),
    ("ike_crypto_profiles", "ike_crypto_profile", _FOLDER_REMOTE_NETWORKS),
    ("ipsec_crypto_profiles", "ipsec_crypto_profile", _FOLDER_REMOTE_NETWORKS),
    ("anti_spyware_profiles", "anti_spyware_profile", "customer"),
    ("vulnerability_profiles", "vulnerability_protection_profile", "customer"),
    ("dns_security_profiles", "dns_security_profile", "customer"),
    ("decryption_profiles", "decryption_profile", "customer"),
    ("file_blocking_profiles", "file_blocking_profile", "customer"),
    ("wildfire_profiles", "wildfire_antivirus_profile", "customer"),
    ("url_access_profiles", "url_access_profile", "customer"),
    # GP & identity & network infrastructure — no inter-object dependencies,
    # so they join Tier 0.  Folder-in-payload: these SDK create() models carry
    # the folder as a regular field.
    ("qos_profiles", "qos_profile", _FOLDER_REMOTE_NETWORKS),
    ("internal_dns_servers", "internal_dns_server", _FOLDER_REMOTE_NETWORKS),
    ("authentication_profiles", "authentication_profile", "customer"),
    ("saml_server_profiles", "saml_server_profile", "customer"),
    ("radius_server_profiles", "radius_server_profile", "customer"),
    ("ldap_server_profiles", "ldap_server_profile", "customer"),
    ("mobile_agent_auth_settings", "auth_setting", _FOLDER_MOBILE_USERS),
    ("mobile_agent_agent_profiles", "agent_profile", _FOLDER_MOBILE_USERS),
    ("forwarding_profiles", "forwarding_profile", _FOLDER_MOBILE_USERS),
    # ── Tier 1 ────────────────────────────────────────────────────────────
    ("addresses", "address", "customer"),
    ("service_groups", "service_group", "customer"),
    ("log_forwarding_profiles", "log_forwarding_profile", "customer"),
    ("zone_protection_profiles", "zone_protection_profile", "customer"),
    ("hip_objects", "hip_object", "customer"),
    # Groups the Tier 0 security profiles; rules reference the group by name
    ("profile_groups", "profile_group", "customer"),
    # ── Tier 2 ────────────────────────────────────────────────────────────
    ("address_groups", "address_group", "customer"),
    ("application_groups", "application_group", "customer"),
    # ── Tier 3 ────────────────────────────────────────────────────────────
    ("hip_profiles", "hip_profile", "customer"),
    ("zones", "security_zone", "customer"),
]

# The rulebase selector is a create() kwarg, never a payload field — and the
# SDK spells it differently per rule type: security, decryption and
# app-override take `rulebase=`, NAT takes `position=`.
_RULE_ORDER: list[tuple[str, str, dict[str, str]]] = [
    ("security_rules_pre", "security_rule", {"rulebase": "pre"}),
    ("security_rules_post", "security_rule", {"rulebase": "post"}),
    ("nat_rules_pre", "nat_rule", {"position": "pre"}),
    ("nat_rules_post", "nat_rule", {"position": "post"}),
    ("decryption_rules", "decryption_rule", {"rulebase": "pre"}),
    ("app_override_rules", "app_override_rule", {"rulebase": "pre"}),
]

# Backups written before the extractor split NAT rules by rulebase put them all
# under one flat key; replay those as pre-rules.
_LEGACY_NAT_ORDER: tuple[str, str, dict[str, str]] = ("nat_rules", "nat_rule", {"position": "pre"})

# GP resources whose create() takes the folder as a keyword argument, not a
# payload field — the Mobile-Users API sends it as a query parameter and the
# create models reject a folder key in the body (extra="forbid").
_FOLDER_KWARG_ORDER: list[tuple[str, str, str]] = [
    ("mobile_agent_tunnel_profiles", "tunnel_profile", _FOLDER_MOBILE_USERS),
    ("mobile_agent_infrastructure", "infrastructure_settings", _FOLDER_MOBILE_USERS),
]

# Deployment resources the API scopes implicitly; a folder in the body is rejected
_FOLDERLESS_RESOURCES = frozenset({"bandwidth_allocation"})

_DEPLOY_ORDER: list[tuple[str, str, str]] = [
    ("ike_gateways", "ike_gateway", _FOLDER_REMOTE_NETWORKS),
    ("ipsec_tunnels", "ipsec_tunnel", _FOLDER_REMOTE_NETWORKS),
    ("remote_networks", "remote_network", _FOLDER_REMOTE_NETWORKS),
    ("service_connections", "service_connection", _FOLDER_SERVICE_CONNECTIONS),
    ("bandwidth_allocations", "bandwidth_allocation", _FOLDER_REMOTE_NETWORKS),
]

# PAN-supplied content lives in the predefined snippets. It is already present
# in every tenant and cannot be created inside a folder, so it is never cloned.
_PREDEFINED_FIELDS = ("snippet", "override_loc")

_IP_RE = re.compile(
    r"\b((?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?))"
    r"((?:/\d{1,2})?)\b"
)


@dataclass
class PushResult:
    resource_type: str
    name: str
    # "created" | "skipped" | "overwritten" | "dry_run" | "failed" | "predefined"
    # | "ref_skipped"
    status: str
    detail: str = ""


@dataclass
class CloneReport:
    source_file: str
    target_folder: str
    target_tenant_id: str
    dry_run: bool
    results: list[PushResult] = field(default_factory=list)
    psk_warnings: list[str] = field(default_factory=list)
    preflight: PreflightResult | None = None

    # ── Counts ──────────────────────────────────────────────────────────
    @property
    def created(self) -> int:
        return sum(1 for r in self.results if r.status in ("created", "dry_run"))

    @property
    def skipped(self) -> int:
        return sum(1 for r in self.results if r.status == "skipped")

    @property
    def overwritten(self) -> int:
        return sum(1 for r in self.results if r.status == "overwritten")

    @property
    def failed(self) -> int:
        return sum(1 for r in self.results if r.status == "failed")

    @property
    def predefined(self) -> int:
        return sum(1 for r in self.results if r.status == "predefined")

    @property
    def ref_skipped(self) -> int:
        return sum(1 for r in self.results if r.status == "ref_skipped")

    def to_markdown(self) -> str:
        lines: list[str] = []
        if self.preflight and self.preflight.blocked and not self.dry_run:
            mode = "BLOCKED BY PREFLIGHT"
        else:
            mode = "DRY RUN PREVIEW" if self.dry_run else "PUSH COMPLETE"
        lines.append(f"# SCM Config Clone — {mode}")
        lines.append(f"\n**Source:** `{self.source_file}`  ")
        lines.append(f"**Target folder:** `{self.target_folder}`  ")
        if self.target_tenant_id:
            lines.append(f"**Target tenant:** `{self.target_tenant_id}`  ")
        lines.append("")

        action = "Would create" if self.dry_run else "Created"
        lines.append("## Summary\n")
        lines.append("| Outcome | Count |")
        lines.append("|---|---|")
        lines.append(f"| {action} | {self.created} |")
        lines.append(f"| Skipped (conflict) | {self.skipped} |")
        if self.predefined:
            lines.append(f"| Skipped (PAN predefined) | {self.predefined} |")
        if self.ref_skipped:
            lines.append(f"| Skipped (preflight) | {self.ref_skipped} |")
        if not self.dry_run:
            lines.append(f"| Overwritten | {self.overwritten} |")
        lines.append(f"| Failed | {self.failed} |")
        lines.append(f"| **Total** | **{len(self.results)}** |")

        if self.preflight:
            lines += self.preflight.to_markdown(self.dry_run)

        if self.psk_warnings:
            lines.append("\n## ⚠️ PSK Placeholders — Set Before Committing\n")
            lines.append("The following IKE gateways had their pre-shared keys replaced:")
            for w in self.psk_warnings:
                lines.append(f"- `{w}`")
            lines.append(
                "\nSet the real PSK via SCM UI or `scm_ike_gateway_update` before pushing commit."
            )

        # Group results by type
        by_type: dict[str, list[PushResult]] = {}
        for r in self.results:
            by_type.setdefault(r.resource_type, []).append(r)

        if self.results:
            lines.append("\n## Detail\n")
            for rtype, items in by_type.items():
                lines.append(f"### {rtype} ({len(items)})\n")
                lines.append("| Name | Status | Detail |")
                lines.append("|---|---|---|")
                for r in items:
                    lines.append(f"| `{r.name}` | {r.status} | {r.detail} |")
                lines.append("")

        if self.failed > 0:
            lines.append("\n## ❌ Failures\n")
            for r in self.results:
                if r.status == "failed":
                    lines.append(f"- **{r.resource_type}** `{r.name}`: {r.detail}")

        return "\n".join(lines)


def _strip_system_fields(obj: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in obj.items() if k not in _SYSTEM_FIELDS}


def _is_predefined(obj: dict[str, Any]) -> bool:
    """True for PAN-supplied objects — those sourced from a predefined snippet."""
    return any(str(obj.get(f) or "").startswith("predefined") for f in _PREDEFINED_FIELDS)


def _drop_nulls(value: Any) -> Any:
    """Drop null fields, recursively.

    SCM response models serialise every unset field as null, but the create
    models reject null where they expect a value or their own default — an
    app-override rule read back with "application": null cannot be replayed.
    """
    if isinstance(value, dict):
        return {k: _drop_nulls(v) for k, v in value.items() if v is not None}
    if isinstance(value, list):
        return [_drop_nulls(v) for v in value]
    return value


# Threat profiles whose rules SCM reads back with action {} when the rule uses
# the signature's default action.  Create rejects both {} and {"default": {}}
# ("missing node 'action'"); omitting the key round-trips back to {}.
_THREAT_RULE_PROFILES = frozenset({"anti_spyware_profiles", "vulnerability_profiles"})


def _drop_empty_actions(obj: dict[str, Any]) -> None:
    for rule in obj.get("rules") or []:
        if isinstance(rule, dict) and rule.get("action") == {}:
            del rule["action"]


def _anonymise_ips(obj: dict[str, Any], ip_map: dict[str, str]) -> dict[str, Any]:
    """Replace IPv4 addresses in a dict (recursively) with template vars."""
    text = json.dumps(obj)

    def _replace(m: re.Match[str]) -> str:
        ip = m.group(1)
        suffix = m.group(2)
        if ip not in ip_map:
            n = len(ip_map) + 1
            ip_map[ip] = f"{{{{IP_{n}}}}}"
        return str(ip_map[ip]) + str(suffix)

    return dict(json.loads(_IP_RE.sub(_replace, text)))


def _scrub_psk(obj: dict[str, Any], gateway_name: str) -> tuple[dict[str, Any], bool]:
    """Replace PSK in an IKE gateway dict. Returns (modified_obj, was_scrubbed)."""
    obj = copy.deepcopy(obj)
    scrubbed = False
    try:
        auth = obj.get("authentication", {})
        if "pre_shared_key" in auth:
            auth["pre_shared_key"]["key"] = f"CHANGEME_{gateway_name}"
            scrubbed = True
        elif isinstance(auth.get("pre_shared_key"), str):
            auth["pre_shared_key"] = f"CHANGEME_{gateway_name}"
            scrubbed = True
    except Exception:
        pass
    return obj, scrubbed


def _apply_name_prefix(obj: dict[str, Any], prefix: str) -> dict[str, Any]:
    if prefix and "name" in obj:
        obj = dict(obj)
        obj["name"] = f"{prefix}{obj['name']}"
    return obj


def _sanitise(
    obj: dict[str, Any],
    *,
    target_folder: str,
    name_prefix: str,
    anonymise_ips: bool,
    ip_map: dict[str, str],
    is_ike_gateway: bool = False,
    set_folder: bool = True,
) -> tuple[dict[str, Any], str | None]:
    """
    Returns (sanitised_obj, psk_warning_or_None).
    """
    o = _drop_nulls(_strip_system_fields(copy.deepcopy(obj)))
    # SCM models accept exactly one container, so the source snippet/device has
    # to go before the target folder is set.
    o.pop("snippet", None)
    o.pop("device", None)
    # Resources whose folder travels as a create() kwarg (GP Mobile-Users API)
    # must not carry a folder key in the payload at all.
    if set_folder:
        o["folder"] = target_folder
    else:
        o.pop("folder", None)

    psk_warning: str | None = None
    if is_ike_gateway:
        name = obj.get("name", "unknown")
        o, scrubbed = _scrub_psk(o, name)
        if scrubbed:
            psk_warning = f"{name_prefix}{name}" if name_prefix else name

    if name_prefix:
        o = _apply_name_prefix(o, name_prefix)

    if anonymise_ips:
        o = _anonymise_ips(o, ip_map)

    return o, psk_warning


def _to_update_model(resource: Any, payload: dict[str, Any]) -> Any:
    """Wrap *payload* in whatever update model this resource's update() takes.

    Every SDK resource types its update() first argument as its own
    ``*UpdateModel``; passing a bare dict raises inside the SDK.
    """
    try:
        # eval_str resolves the annotation when the defining module uses
        # postponed evaluation, where it would otherwise arrive as a string.
        sig = inspect.signature(resource.update, eval_str=True)
    except Exception:
        sig = inspect.signature(resource.update)
    params = [p for n, p in sig.parameters.items() if n != "self"]
    annotation = params[0].annotation if params else None
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation(**payload)
    return payload


class _RestResource:
    """Minimal create/fetch/update adapter for config resources pan-scm-sdk
    does not wrap, so ``_push_one`` can treat them like SDK resources."""

    def __init__(self, session: Any, url: str) -> None:
        self._session = session
        self._url = url

    @staticmethod
    def _check(resp: Any) -> Any:
        if not resp.ok:
            # Body carries the SCM error text ("Object already exists", ...)
            # that the conflict detection in _push_one matches on.
            raise RuntimeError(f"HTTP {resp.status_code}: {resp.text[:300]}")
        return resp.json() if resp.content else {}

    def create(self, data: dict[str, Any]) -> Any:
        return self._check(self._session.post(self._url, json=data, timeout=30))

    def fetch(self, name: str, folder: str) -> Any:
        body = self._check(
            self._session.get(self._url, params={"name": name, "folder": folder}, timeout=30)
        )
        items = body.get("data", [body]) if isinstance(body, dict) else body
        if not items:
            raise RuntimeError(f"{name!r} not found in folder {folder!r}")
        return type("Existing", (), {"id": items[0].get("id")})()

    def update(self, data: dict[str, Any]) -> Any:
        # The container is fixed at create time; PUT bodies carry neither it nor the id
        payload = {k: v for k, v in data.items() if k not in ("id", "folder", "snippet", "device")}
        return self._check(self._session.put(f"{self._url}/{data['id']}", json=payload, timeout=30))


# Resources with no pan-scm-sdk wrapper (0.15.1), pushed via raw REST
_REST_ONLY_RESOURCES: dict[str, str] = {
    "profile_group": "https://api.sase.paloaltonetworks.com/sse/config/v1/profile-groups",
}


# Resources the API never reports as a name conflict: a duplicate create is
# accepted under a generated name (e.g. GP auth settings → "UserAuth_<ts>").
_RENAMES_ON_DUPLICATE = frozenset({"auth_setting"})


def _exists(
    resource: Any, name: str, payload: dict[str, Any], create_kwargs: dict[str, str]
) -> bool:
    folder = create_kwargs.get("folder") or payload.get("folder") or _FOLDER_MOBILE_USERS
    try:
        resource.fetch(name=name, folder=folder)
    except Exception:
        return False
    return True


def _rest_create_fallback(
    client: Any, resource: Any, exc: Exception, create_kwargs: dict[str, str]
) -> _RestResource | None:
    """REST adapter for a create the SDK rejected client-side.

    The SDK create models are stricter than SCM — e.g. their name pattern
    forbids spaces, which SCM accepts — so a local validation error is retried
    as a raw POST.  Only folder-in-payload creates qualify: rulebase and folder
    kwargs travel as query parameters the adapter does not send.
    """
    if "validation error" not in str(exc).lower() or create_kwargs:
        return None
    endpoint = getattr(resource, "ENDPOINT", None)
    session = getattr(client, "session", None)
    base = getattr(client, "api_base_url", None)
    if not (endpoint and session is not None and base):
        return None
    logger.info("clone_sdk_validation_rest_fallback", endpoint=endpoint)
    return _RestResource(session, f"{base}{endpoint}")


# pan-scm-sdk (0.15.1) create()/update() serialise these without by_alias, so
# aliased fields never reach SCM and are dropped without an error: a URL
# profile's "continue" action, a HIP object's "is" criteria, vulnerability
# rules' "vendor-id".  They are pushed over REST with the keys renamed instead.
_ALIASED_KEYS: dict[str, dict[str, str]] = {
    "url_access_profile": {"continue_": "continue"},
    "hip_object": {"is_": "is"},
    "vulnerability_protection_profile": {"vendor_id": "vendor-id"},
}


def _rename_keys(value: Any, renames: dict[str, str]) -> Any:
    if isinstance(value, dict):
        return {renames.get(k, k): _rename_keys(v, renames) for k, v in value.items()}
    if isinstance(value, list):
        return [_rename_keys(v, renames) for v in value]
    return value


class _AliasedRestResource(_RestResource):
    """REST adapter that sends the API's field names for SDK-aliased keys."""

    def __init__(self, session: Any, url: str, renames: dict[str, str]) -> None:
        super().__init__(session, url)
        self._renames = renames

    def create(self, data: dict[str, Any]) -> Any:
        return super().create(_rename_keys(data, self._renames))

    def update(self, data: dict[str, Any]) -> Any:
        return super().update(_rename_keys(data, self._renames))


def _resource(client: Any, sdk_attr: str) -> Any:
    if sdk_attr in _REST_ONLY_RESOURCES:
        try:
            return getattr(client, sdk_attr)
        except AttributeError:
            return _RestResource(client.session, _REST_ONLY_RESOURCES[sdk_attr])
    resource = getattr(client, sdk_attr)
    renames = _ALIASED_KEYS.get(sdk_attr)
    endpoint = getattr(resource, "ENDPOINT", None)
    base = getattr(client, "api_base_url", None)
    if renames and endpoint and base:
        return _AliasedRestResource(client.session, f"{base}{endpoint}", renames)
    return resource


def _push_one(
    client: Any,
    sdk_attr: str,
    payload: dict[str, Any],
    on_conflict: str,
    dry_run: bool,
    resource_type: str,
    create_kwargs: dict[str, str] | None = None,
) -> PushResult:
    name = payload.get("name", "<unknown>")
    create_kwargs = create_kwargs or {}
    if dry_run:
        shown_folder = str(create_kwargs.get("folder") or payload.get("folder", ""))
        detail = f"would create in folder '{shown_folder}'"
        if create_kwargs:
            detail += " (" + ", ".join(f"{k}={v}" for k, v in create_kwargs.items()) + ")"
        return PushResult(resource_type, name, "dry_run", detail)
    try:
        resource = _resource(client, sdk_attr)
        if sdk_attr in _RENAMES_ON_DUPLICATE and _exists(resource, name, payload, create_kwargs):
            if on_conflict == "skip":
                return PushResult(resource_type, name, "skipped", "already exists")
            return PushResult(
                resource_type, name, "failed", "exists; overwrite unsupported for this type"
            )
        try:
            resource.create(payload, **create_kwargs)
        except Exception as exc:
            rest = _rest_create_fallback(client, resource, exc, create_kwargs)
            if rest is None:
                raise
            rest.create(payload)
        logger.info("clone_object_created", type=resource_type, name=name)
        return PushResult(resource_type, name, "created")
    except Exception as exc:
        err = str(exc)
        is_conflict = any(
            x in type(exc).__name__ for x in ("Conflict", "NameNotUnique", "ObjectNotUnique")
        )
        if not is_conflict:
            is_conflict = any(
                p in err.lower() for p in ("already exists", "name not unique", "conflict")
            )
        if is_conflict and on_conflict == "skip":
            return PushResult(resource_type, name, "skipped", "already exists")
        if is_conflict and on_conflict == "overwrite":
            try:
                resource = _resource(client, sdk_attr)
                # Forward the create kwargs (e.g. rulebase=) but keep the
                # folder single-sourced: it may ride in create_kwargs for
                # folder-kwarg resources instead of the payload.
                fetch_kwargs: dict[str, str] = {"name": name}
                if "folder" in create_kwargs:
                    fetch_kwargs["folder"] = str(create_kwargs["folder"])
                else:
                    fetch_kwargs["folder"] = payload.get("folder", "")
                for k, v in create_kwargs.items():
                    if k != "folder":
                        fetch_kwargs[k] = str(v)
                existing = resource.fetch(**fetch_kwargs)
                payload_with_id = dict(payload)
                if hasattr(existing, "id"):
                    payload_with_id["id"] = str(existing.id)
                resource.update(_to_update_model(resource, payload_with_id), **create_kwargs)
                return PushResult(resource_type, name, "overwritten")
            except Exception as upd_exc:
                return PushResult(resource_type, name, "failed", str(upd_exc)[:120])
        logger.warning("clone_object_failed", type=resource_type, name=name, error=err)
        return PushResult(resource_type, name, "failed", err[:120])


def _planned_batches(
    resources: dict[str, Any],
    *,
    include_deployment: bool,
    skip_rules: bool,
    resource_filter: set[str] | None,
) -> list[tuple[str, str, str, dict[str, Any]]]:
    """(backup key, sdk attr, folder, _process_batch options) in push order."""
    batches: list[tuple[str, str, str, dict[str, Any]]] = []
    for snap_key, sdk_attr, folder in _PUSH_ORDER:
        batches.append((snap_key, sdk_attr, folder, {}))
    for snap_key, sdk_attr, folder in _FOLDER_KWARG_ORDER:
        batches.append((snap_key, sdk_attr, folder, {"folder_kwarg": True}))
    if not skip_rules:
        rule_order = list(_RULE_ORDER)
        if not resources.get("nat_rules_pre") and not resources.get("nat_rules_post"):
            rule_order.append(_LEGACY_NAT_ORDER)
        for snap_key, sdk_attr, rule_kwargs in rule_order:
            batches.append((snap_key, sdk_attr, "customer", {"create_kwargs": rule_kwargs}))
    if include_deployment:
        for snap_key, sdk_attr, folder in _DEPLOY_ORDER:
            batches.append(
                (snap_key, sdk_attr, folder, {"is_ike_gateway": sdk_attr == "ike_gateway"})
            )
    return [
        b
        for b in batches
        if resources.get(b[0]) and not (resource_filter and b[0] not in resource_filter)
    ]


def _run_preflight(
    client: Any,
    resources: dict[str, Any],
    planned_keys: list[str],
    target_folder: str,
    *,
    name_prefix: str,
    on_missing_reference: str,
    on_missing_trust_cert: str,
    inventory: TargetInventory | None,
) -> PreflightResult:
    if on_missing_reference not in MISSING_REFERENCE_MODES:
        raise ValueError(
            f"on_missing_reference must be one of {', '.join(MISSING_REFERENCE_MODES)}"
        )
    if on_missing_trust_cert not in MISSING_TRUST_CERT_MODES:
        raise ValueError(
            f"on_missing_trust_cert must be one of {', '.join(MISSING_TRUST_CERT_MODES)}"
        )
    session = None
    if inventory is None or "decryption_rules" in planned_keys:
        from .extractor import _bearer_session_for

        session = _bearer_session_for(client)
    if inventory is None:
        inventory = fetch_target_inventory(session, target_folder)

    def trust_state() -> str:
        from ..tools.tenant_copy import _forward_trust_state

        try:
            return _forward_trust_state(session)
        except Exception as exc:
            logger.warning("clone_preflight_trust_state_failed", error=str(exc)[:200])
            return "unknown"

    return check_references(
        resources,
        planned_keys,
        inventory,
        name_prefix=name_prefix,
        on_missing_reference=on_missing_reference,
        trust_state=trust_state if session is not None else None,
        on_missing_trust_cert=on_missing_trust_cert,
    )


def clone_config(
    client: Any,
    source_backup_file: str,
    target_folder: str,
    *,
    name_prefix: str = "",
    anonymise_ips: bool = False,
    include_deployment: bool = False,
    skip_rules: bool = False,
    on_conflict: str = "skip",
    dry_run: bool = True,
    resource_filter: set[str] | None = None,
    on_missing_reference: str | None = None,
    on_missing_trust_cert: str = "fail",
    inventory: TargetInventory | None = None,
) -> CloneReport:
    """
    Load *source_backup_file*, sanitise every object, and push to
    *target_folder* on *client*.

    Parameters
    ----------
    client          : Authenticated Scm client.
    source_backup_file : Path to JSON produced by scm_config_backup.
    target_folder   : Destination SCM folder name.
    name_prefix     : Optional prefix applied to every object name.
    anonymise_ips   : Replace IPv4 literals with {{IP_N}} template vars.
    include_deployment : Also clone IKE gateways, IPSec tunnels, RNs, SCs,
                         bandwidth allocations and QoS/DNS infrastructure.
    skip_rules      : Omit all policy rules.
    on_conflict     : 'skip' (default) or 'overwrite'.
    dry_run         : If True, no API writes are made (default: True).
    resource_filter : If set, only process resource types in this set.
    on_missing_reference : Run the reference preflight (clone_preflight.py)
                         against the target before any write: 'fail',
                         'skip_object' or 'strip_member'.  None skips it.
    on_missing_trust_cert : Enabled decrypt rules when the target has no
                         forward-trust certificate: 'fail', 'disable_rule'
                         or 'skip_object'.  Only used with the preflight.
    inventory       : Pre-fetched target inventory (tests); read live if None.

    GlobalProtect and identity coverage: auth settings, tunnel profiles,
    agent profiles, forwarding profiles, portal/gateway infrastructure
    settings (fixed 'Mobile Users' folder) and SAML/Radius/LDAP auth
    profiles (customer folder) are cloned from the backup when present.
    """
    data = json.loads(Path(source_backup_file).read_text())
    resources: dict[str, list[dict[str, Any]]] = data.get("resources", {})

    report = CloneReport(
        source_file=source_backup_file,
        target_folder=target_folder,
        target_tenant_id="",
        dry_run=dry_run,
    )
    ip_map: dict[str, str] = {}
    batches = _planned_batches(
        resources,
        include_deployment=include_deployment,
        skip_rules=skip_rules,
        resource_filter=resource_filter,
    )

    preflight: PreflightResult | None = None
    if on_missing_reference is not None:
        preflight = _run_preflight(
            client,
            resources,
            [b[0] for b in batches],
            target_folder,
            name_prefix=name_prefix,
            on_missing_reference=on_missing_reference,
            on_missing_trust_cert=on_missing_trust_cert,
            inventory=inventory,
        )
        report.preflight = preflight
        if preflight.blocked and not dry_run:
            return report

    def _process_batch(
        snap_key: str,
        sdk_attr: str,
        folder: str,
        *,
        is_ike_gateway: bool = False,
        create_kwargs: dict[str, str] | None = None,
        folder_kwarg: bool = False,
    ) -> None:
        for obj in resources.get(snap_key, []):
            # Checked before sanitising, which drops the source container the
            # predefined marker lives in.
            if _is_predefined(obj):
                report.results.append(
                    PushResult(
                        snap_key,
                        obj.get("name", "<unknown>"),
                        "predefined",
                        "PAN predefined content — already present in every tenant",
                    )
                )
                continue
            oid = (snap_key, str(obj.get("name", "")))
            note = ""
            if preflight is not None:
                if oid in preflight.skip:
                    report.results.append(
                        PushResult(
                            snap_key,
                            obj.get("name", "<unknown>"),
                            "ref_skipped",
                            preflight.skip[oid],
                        )
                    )
                    continue
                stripped = preflight.strip.get(oid)
                if stripped:
                    obj = dict(obj)
                    for fld, bad in stripped.items():
                        obj[fld] = [v for v in obj.get(fld) or [] if v not in bad]
                    note = "stripped " + "; ".join(
                        f"{fld}: {', '.join(sorted(bad))}" for fld, bad in stripped.items()
                    )
            obj_folder = folder if folder != "customer" else target_folder
            o, psk_w = _sanitise(
                obj,
                target_folder=obj_folder,
                name_prefix=name_prefix,
                anonymise_ips=anonymise_ips,
                ip_map=ip_map,
                is_ike_gateway=is_ike_gateway,
                set_folder=not folder_kwarg and sdk_attr not in _FOLDERLESS_RESOURCES,
            )
            if psk_w:
                report.psk_warnings.append(psk_w)
            if snap_key in _THREAT_RULE_PROFILES:
                _drop_empty_actions(o)
            if preflight is not None and oid in preflight.disable:
                o["disabled"] = True
                note = "created disabled — no forward-trust certificate"
            kwargs = dict(create_kwargs or {})
            if folder_kwarg:
                kwargs["folder"] = folder
            result = _push_one(
                client, sdk_attr, o, on_conflict, dry_run, snap_key, create_kwargs=kwargs
            )
            if note:
                result.detail = f"{result.detail}; {note}" if result.detail else note
            report.results.append(result)

    for snap_key, sdk_attr, folder, opts in batches:
        _process_batch(snap_key, sdk_attr, folder, **opts)

    return report
